repository=https://void.voidbr.org/voidlinux/current
repository=https://void.voidbr.org/voidlinux/extra
repository=https://void.voidbr.org/voidlinux/current/nonfree
repository=https://void.voidbr.org/voidlinux/current/multilib
repository=https://void.voidbr.org/voidlinux/current/multilib/nonfree
